import { browser, login, BASE, FIELD_PASS } from './cdp.mjs';
const ck = await login('somsak', FIELD_PASS);
const get = async p => (await fetch(BASE + p, { headers: { cookie: 'cct_s=' + ck } })).json();
const f = await get('/api/field');
const c = f.crew.find(x => x.name === 'Tran Minh Duc');
const doneBefore = c.cps.filter(x => x.actual).length;
const b = await browser();
await b.size(390, 800, true);
await b.go('/api/health', 200);
await b.cookie(ck);
await b.go('/field/' + c.id, 1800);
await b.send('Network.emulateNetworkConditions', { offline: true, latency: 0, downloadThroughput: -1, uploadThroughput: -1 });
await b.eval(`document.querySelector('[data-act="f-confirm"]').click()`);
await new Promise(r => setTimeout(r, 2500));
const box = await b.eval(`localStorage.getItem('cct-outbox-v1')`);
const toast = await b.eval(`document.getElementById('toast').textContent`);
const pendUi = await b.eval(`!!document.querySelector('.tli .pend')`);
const serverWhileOffline = (await get('/api/field')).crew.find(x => x.id === c.id).cps.filter(x => x.actual).length;
await b.send('Network.emulateNetworkConditions', { offline: false, latency: 0, downloadThroughput: -1, uploadThroughput: -1 });
await b.eval(`window.dispatchEvent(new Event('online'))`);
await new Promise(r => setTimeout(r, 3000));
const after = (await get('/api/field')).crew.find(x => x.id === c.id);
const box2 = await b.eval(`localStorage.getItem('cct-outbox-v1')`);
const r = { queued: JSON.parse(box || '[]').length, toast, pendUi, serverWhileOffline, doneBefore, serverAfter: after.cps.filter(x => x.actual).length, outboxAfter: box2, logs: b.logs };
console.log(r);
b.close();
const good = r.queued === 1 && r.serverWhileOffline === doneBefore && r.serverAfter === doneBefore + 1 && JSON.parse(box2 || '[]').length === 0;
console.log(good ? 'PASS offline confirm queued and synced' : 'FAIL offline confirm');
if (!good) process.exitCode = 1;
